/**
 * Immutable Configuration Constants for ChitraSara Compression Engine
 */

export * from './mime';

export const HARDWARE_THRESHOLDS = {
  LOW_RAM_GB: 2,
  BALANCED_RAM_GB: 4,
  LOW_CORES: 2,
  BALANCED_CORES: 4,
  MAX_CANVAS_DIM_LOW: 2048,
  MAX_CANVAS_DIM_BALANCED: 4096,
  MAX_CANVAS_DIM_HIGH: 8192,
  DEFAULT_FALLBACK_CORES: 2,
  WORKER_LIMIT_LOW: 1,
  WORKER_LIMIT_BALANCED_MAX: 4,
  WORKER_LIMIT_HIGH_MAX: 12,
  THUMBNAIL_MAX_DIM_LOW: 80,
  THUMBNAIL_MAX_DIM_DEFAULT: 160,
} as const;

export const ENGINE_DEFAULTS = {
  DEFAULT_QUALITY: 0.75,
  MIN_QUALITY: 0.05,
  MAX_QUALITY: 1.0,
  STEP_DOWN_THRESHOLD_PIXELS: 4096 * 4096, // 16MP threshold for memory step-down
  AUTO_PROCESS_DEFAULT: true,
} as const;

export const SOLVER_DEFAULTS = {
  MIN_QUALITY: 0.15,
  MAX_QUALITY: 1.0,
  DEFAULT_TOLERANCE_RATIO: 0.05, // +/- 5%
  DEFAULT_MAX_ITERATIONS: 7,
  MIN_DIMENSION_WIDTH: 320,
  MIN_DIMENSION_HEIGHT: 320,
  DOWNSCALE_STEP_FACTOR: 0.80,
  MAX_TOTAL_ATTEMPTS: 15,
} as const;

export const WORKER_CONSTANTS = {
  TASK_TIMEOUT_MS: 30000,
  MAX_RETRY_COUNT: 2,
  IDLE_RECLAMATION_MS: 30000,
} as const;

export const QUEUE_LIMITS = {
  MAX_CONCURRENT_DISPATCH_LOW: 1,
  MAX_CONCURRENT_DISPATCH_BALANCED: 4,
  MAX_CONCURRENT_DISPATCH_HIGH: 12,
} as const;
